# Generated by Django 5.1.3 on 2024-12-02 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioartdis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sugerencia',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias_respondidas', to='biblioartdis.usuario'),
        ),
    ]
