# Generated by Django 5.1.3 on 2025-04-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioartdis', '0002_sugerencia_fecha_respuesta_sugerencia_respondido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='enlace',
            field=models.URLField(blank=True, help_text='Enlace externo (opcional)', max_length=500, null=True),
        ),
    ]
